version: 2.1

orbs:
  composer: itinerisltd/composer@0.3
  codecov: codecov/codecov@1

workflows:
  test:
    jobs:
      - composer/install:
          name: test-latest
          executor: composer/latest
          post-steps:
            - composer/exec:
                command: test:coverage
            - codecov/upload:
                file: tests/_output/coverage.xml

      - composer/install:
          name: test-7.4
          executor: composer/php-74
          post-steps:
            - composer/exec:
                command: test

      - composer/install:
          name: test-7.3
          executor: composer/php-73
          post-steps:
            - composer/exec:
                command: test

      - composer/install:
          name: test-7.2
          executor: composer/php-72
          post-steps:
            - composer/exec:
                command: test

      - composer/install:
          name: style-check
          post-steps:
            - composer/exec:
                command: style:check

      - composer/install:
          name: style-check-php-7.2
          executor: composer/php-72
          post-steps:
            - composer/exec:
                command: style:check
